### ISSUE TITLE
Incorrect example URL in /validations documentation

### ISSUE THREAD

**Issue by stevegrunwell** [WhiteHouse/write-api-beta-testing#7]
The /validations endpoint requires authentication via the `api_key` argument, but the example URL provided is https://api.whitehouse.gov/v1/validations.json?key=asY1k9uCQY7Hg8MCBaa, which returns a 401 Unauthorized status due to the missing argument. This demo URI should be: 
https://api.whitehouse.gov/v1/validations.json?api_key=asY1k9uCQY7Hg8MCBaa

![validations-mismatch](https://cloud.githubusercontent.com/assets/233836/3027856/d2d5359a-e026-11e3-84ea-6ad181dcdee2.png)

**Update:** Failed to specify, this is on https://11111011100.petitions.whitehouse.gov/developers

**Comment by stevegrunwell** [comment]
My apologies, this would have been more appropriate on the WriteAPI_Beta repo - [pull request opened over there](https://github.com/WhiteHouse/WriteAPI_Beta/pull/92).

Coffee apparently hasn't kicked in yet.

**Comment by bryanhirsch** [comment]
@stevegrunwell, thanks! We have fixed this internally. Docs will be fixed with a release coming out soon.
